### ISSUE TITLE
fix & some update

### ISSUE THREAD

**Issue by 0xvgd** [polymorpher/dot-country-embedder#4]
![image](https://github.com/polymorpher/dot-country-embedder/assets/18642714/9223311d-4afa-4ae8-a603-3f0fb1532633)

less than 0.2 second now for fast internet after fixing a few things, so it doesn't matter much

deployed https://blog.li.country/

would be nice to put children of <head> and <body> stuff in the right place, instead of inserting them a div, which violates html syntax. At least <head> children should be inserted into the real head, so the browser can correctly display favicon, title, and description of the page.

we should also cache substack's response instead of making axios to query it every time.

![image](https://github.com/polymorpher/dot-country-embedder/assets/18642714/9a27f4d8-df67-4eb4-8de6-5bf987d9eaf2)
![image](https://github.com/polymorpher/dot-country-embedder/assets/18642714/d923d906-b249-4451-b77d-c5bcbd8fce14)

blog.s.country the share button is not working. Some widgets, such as the pool, is not working either (I am hiding it with CSS). I think some scripts are not executed properly. Can you take a look and help fix?

we could replace the share button with our own if it is easier

also the mobile responsiveness is sort of broken blog.s.country

**Comment by 0xvgd** [comment]
@polymorpher is blog.s.country for stse.substack.com?
I can't see share button and pool widget from stse.substack.com, can you please upload the screenshot?

**Comment by 0xvgd** [comment]
I just figured out that share button would be
![image](https://github.com/polymorpher/dot-country-embedder/assets/18642714/f2c78c1e-dbdb-47f2-95f7-fdc181598215)

**Comment by 0xvgd** [comment]
> less than 0.2 second now for fast internet after fixing a few things, so it doesn't matter much

It's because the DOM is rendered before the style is fully loaded.
If the dom was from initial doc request, we can use window.onload to catch when all dependent resources are fully loaded, but in our case, the dom is updated dynamically via javascript and window.onload doesn't work for dynamically updated resources.
Not sure how to handle this. 😉

**Comment by polymorpher** [comment]
> @polymorpher is blog.s.country for stse.substack.com? I can't see share button and pool widget from stse.substack.com, can you please upload the screenshot?

You can find them in individual articles

**Comment by polymorpher** [comment]
> > less than 0.2 second now for fast internet after fixing a few things, so it doesn't matter much
> 
> It's because the DOM is rendered before the style is fully loaded. If the dom was from initial doc request, we can use window.onload to catch when all dependent resources are fully loaded, but in our case, the dom is updated dynamically via javascript and window.onload doesn't work for dynamically updated resources. Not sure how to handle this. 😉

See if you can artificially trigger some events? e.g. https://stackoverflow.com/questions/9642823/force-a-window-onload-event-in-javascript

Need to find out which events are listened to - I guess you can analyze the scripts themselves or debug attached event listeners after the page is loaded. I haven't done the latter systematically before but I think it might work. The former might be easier. Or you can just trigger a few common ones (e.g. onload) and see if it works well enough already
