### ISSUE TITLE
Invalid import assertion

### ISSUE THREAD

**Issue by nicolo-ribaudo** [polymorpher/dot-country-embedder#6]
Hi!

I noticed that you are using an `integrity` assertion, that is invalid and it's currently being ignored by browsers.

We are updating the import assertions behavior to throw on unknown ones, so you might want to remove it.

https://github.com/polymorpher/dot-country-embedder/blob/43bb833268930ef30db870c91bb80a16e6881ac1/server/src/og.ts#L4

**Comment by polymorpher** [comment]
Fixed, thanks
